// <auto-generated />
using CadMedicoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadMedicoApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CadMedicoApi.Models.CidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Parana",
                            Nome = "Apucarana"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Paraná",
                            Nome = "Londrina"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Paraná",
                            Nome = "Curitiba"
                        },
                        new
                        {
                            Id = 4,
                            Estado = "Paraná",
                            Nome = "Maringá"
                        });
                });

            modelBuilder.Entity("CadMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Obstetra"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Podólogo"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Cardiologista"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Geriatra"
                        });
                });

            modelBuilder.Entity("CadMedicoApi.Models.MedicoCidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.ToTable("MedicoCidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            CidadeId = 1
                        },
                        new
                        {
                            MedicoId = 1,
                            CidadeId = 2
                        },
                        new
                        {
                            MedicoId = 3,
                            CidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            CidadeId = 4
                        });
                });

            modelBuilder.Entity("CadMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "EspecialidadeId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("MedicoEspecialidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            EspecialidadeId = 1
                        },
                        new
                        {
                            MedicoId = 1,
                            EspecialidadeId = 2
                        },
                        new
                        {
                            MedicoId = 3,
                            EspecialidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            EspecialidadeId = 4
                        });
                });

            modelBuilder.Entity("CadMedicoApi.Models.MedicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crm = "33",
                            Nome = "Eduardo",
                            Telefone = "3344-0099"
                        },
                        new
                        {
                            Id = 2,
                            Crm = "33",
                            Nome = "Eduardo",
                            Telefone = "3344-0099"
                        },
                        new
                        {
                            Id = 3,
                            Crm = "35",
                            Nome = "Manoel",
                            Telefone = "3344-0099"
                        },
                        new
                        {
                            Id = 4,
                            Crm = "36",
                            Nome = "Antonio",
                            Telefone = "3344-0099"
                        },
                        new
                        {
                            Id = 5,
                            Crm = "37",
                            Nome = "Chico",
                            Telefone = "3344-0099"
                        });
                });

            modelBuilder.Entity("CadMedicoApi.Models.PrivilegioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Privilegios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Master"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Adm"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "User"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "UserMed"
                        });
                });

            modelBuilder.Entity("CadMedicoApi.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivilegioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "Eduardo",
                            Nome = "Eduardo",
                            PrivilegioId = 1,
                            Senha = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Login = "Chicao",
                            Nome = "Chico",
                            PrivilegioId = 2,
                            Senha = "4321"
                        },
                        new
                        {
                            Id = 3,
                            Login = "Cleitin",
                            Nome = "Cleitin",
                            PrivilegioId = 3,
                            Senha = "0987"
                        },
                        new
                        {
                            Id = 4,
                            Login = "Joao",
                            Nome = "João",
                            PrivilegioId = 5,
                            Senha = "9087"
                        });
                });

            modelBuilder.Entity("CadMedicoApi.Models.MedicoCidade", b =>
                {
                    b.HasOne("CadMedicoApi.Models.CidadeModel", "Cidade")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CadMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.HasOne("CadMedicoApi.Models.EspecialidadeModel", "Especialidade")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CadMedicoApi.Models.CidadeModel", b =>
                {
                    b.Navigation("MedicoCidade");
                });

            modelBuilder.Entity("CadMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Navigation("MedicoEspecialidade");
                });

            modelBuilder.Entity("CadMedicoApi.Models.MedicoModel", b =>
                {
                    b.Navigation("MedicoCidade");

                    b.Navigation("MedicoEspecialidade");
                });
#pragma warning restore 612, 618
        }
    }
}
